import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import { logoutAction } from "@/features/auth/actions/logout";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
    const testWs = "test-workspace-123";

    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col">
                <nav
                    style={{
                        padding: "1rem",
                        borderBottom: "1px solid #ccc",
                        marginBottom: "1rem",
                        display: "flex",
                        gap: "1rem",
                        backgroundColor: "#f9f9f9",
                        color: "#000",
                        alignItems: "center",
                        flexWrap: "wrap",
                    }}
                >
                    <Link href="/">Dashboard Home</Link>
                    <Link href={`/${testWs}`}>Workspace Overview</Link>
                    <Link href={`/${testWs}/documents`}>Documents</Link>
                    <Link href={`/${testWs}/tasks`}>Tasks</Link>
                    <Link href={`/${testWs}/chat`}>Chat</Link>
                    <Link href={`/${testWs}/analytics`}>Analytics</Link>
                    <Link href={`/${testWs}/settings`}>Settings</Link>
                    <Link href="/unauthorized">Unauthorized Test</Link>
                    <div style={{ flexGrow: 1 }}></div>
                    <form action={logoutAction}>
                        <button
                            type="submit"
                            style={{
                                cursor: "pointer",
                                background: "#ff4d4f",
                                color: "white",
                                border: "none",
                                padding: "0.25rem 0.5rem",
                                borderRadius: "4px",
                            }}
                        >
                            Logout
                        </button>
                    </form>
                </nav>
                <main className="flex-1">{children}</main>
            </body>
        </html>
    );
}
