import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

import { auth } from "@/features/auth/lib/auth";
import { UserDropdown } from "@/components/layout/user-dropdown";
import { UnauthNavActions } from "@/components/layout/unauth-nav-actions";

export default async function RootLayout({ children }: LayoutProps<"/">) {
    const session = await auth();
    let navUser = session?.user;

    if (navUser?.id) {
        // Fetch fresh user data so the avatar updates immediately after an upload
        const { rawDb } = await import("@/lib/db");
        const dbUser = await rawDb.user.findUnique({
            where: { id: navUser.id },
            select: { name: true, image: true, email: true },
        });
        if (dbUser) {
            navUser = { ...navUser, ...dbUser };
        }
    }

    const testWs = "test-workspace-123";

    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col">
                <nav
                    style={{
                        padding: "1rem",
                        borderBottom: "1px solid #ccc",
                        marginBottom: "1rem",
                        display: "flex",
                        gap: "1rem",
                        backgroundColor: "#f9f9f9",
                        color: "#000",
                        alignItems: "center",
                        flexWrap: "wrap",
                    }}
                >
                    <Link href="/" className="font-bold text-xl">
                        App Logo
                    </Link>

                    {session?.user ? (
                        <>
                            <Link href="/dashboard">Dashboard</Link>
                            <Link href={`/${testWs}`}>Workspace Overview</Link>
                            <Link href={`/${testWs}/documents`}>Documents</Link>
                            <Link href={`/${testWs}/tasks`}>Tasks</Link>
                            <Link href={`/${testWs}/chat`}>Chat</Link>
                            <Link href={`/${testWs}/analytics`}>Analytics</Link>
                            <Link href={`/${testWs}/settings`}>Settings</Link>
                            <div style={{ flexGrow: 1 }}></div>
                            <UserDropdown user={navUser!} />
                        </>
                    ) : (
                        <>
                            <div style={{ flexGrow: 1 }}></div>
                            <UnauthNavActions />
                        </>
                    )}
                </nav>
                <main className="flex-1">{children}</main>
            </body>
        </html>
    );
}
